# -*- coding: utf-8 -*-
"""
Created on Fri Dec 21 12:30:02 2018

@author: vcian
"""

"""Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
It can be verified that T285 = P165 = H143 = 40755.

Find the next triangle number that is also pentagonal and hexagonal."""

def is_pent(n):
    try:
        return (24 * n + 1)**.5 % 6 == 5
    except:
        return False    
    
def is_tri(n):
    try:
        return (8*n + 1)**.5 % 2 == 1
    except:
        return False

# First two values:
# n = 1
# n = 143
n = 144    
while True:
    hn = n * (2*n - 1)
    if is_pent(hn) and is_tri(hn):
        print("h_{} = {}".format(n,hn))
        break
    n += 1