# -*- coding: utf-8 -*-
"""
Created on Wed Dec 19 10:00:46 2018

@author: vcian
"""

"""How many distinct terms are in the sequence generated by a^b for 2 ≤ a ≤ 100 and 2 ≤ b ≤ 100?"""

def power_sieve(n):
    if type(n) != int:
        raise TypeError("n must be an int.")
    if n < 2:
        raise ValueError("n must be greater than or equal to 2.")
        
    num_list = list(range(2,n+1))
    for k in range(len(num_list)):
        i = num_list[k]
        if i == 0:
            continue
        j = 2
        while i**j <= n:
            try:
                ind = num_list.index(i**j)
                num_list[ind] = 0
                j += 1
            except ValueError:
                j += 1
    
    while True:
        try:
            num_list.remove(0)
        except ValueError:
            return num_list
